// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for iOS. Re-run FlutterFire CLI.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for macOS. Re-run FlutterFire CLI.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for Windows. Re-run FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for Linux. Re-run FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0B9-sYd6ZlUbfEbCQhX_bDWSUfAp97vI',
    appId: '1:574522238673:web:39a74ae71bd23fedce47f0',
    messagingSenderId: '574522238673',
    projectId: 'doctack-a7e33',
    authDomain: 'doctack-a7e33.firebaseapp.com',
    storageBucket: 'doctack-a7e33.firebasestorage.app',
    measurementId: 'G-V9J0LSY8H3',
  );

  // ✅ Correct Web configuration for your project (fully synced with Firebase Console)

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgpF1a1eNP4hvcbrtdU0PDPSESOdlzHIQ',
    appId: '1:574522238673:android:6633342c91ce95ecce47f0',
    messagingSenderId: '574522238673',
    projectId: 'doctack-a7e33',
    storageBucket: 'doctack-a7e33.firebasestorage.app',
  );

  // ✅ Android configuration (unchanged)
}